apiVersion: v1
kind: Service
metadata:
  name: inventario-service-bg
spec:
  type: NodePort
  selector:
    app: inventario
    version: blue # Inicia enviando TODO el tráfico a Blue
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
