name: ci/cd pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout del código
        uses: actions/checkout@v3

      - name: configurar node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: instalar dependencias
        run: npm ci

      - name: ejecutar pruebas
        run: npm test

  build-push:
    needs: build-test # fail-fast: solo se ejecuta si build-test es exitoso
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # necesario para publicar en ghcr.io

    steps:
      - name: checkout del código
        uses: actions/checkout@v3

      - name: login en github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: construir y publicar imagen docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/raet0/inventario-app:${{ github.sha }}
            ghcr.io/raet0/inventario-app:latest

  
